version: '3'
services:
  posts:
    build: 
      context: ./posts
      args:
        NODE_ENV: development
        PORT: 4000
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
    volumes:
      - ./posts/:/app:ro
      - /posts/node_modules
    command: ["npm", "start"]
  comments:
    build: 
      context: ./comments
      args:
        NODE_ENV: development
        PORT: 4001
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - NODE_ENV=development
    volumes:
      - ./comments:/app:ro
      - /app/node_modules
    command: ["npm", "start"]
  query:
    build: 
      context: ./query
      args:
        NODE_ENV: development
        PORT: 4002
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - NODE_ENV=development
    volumes:
      - ./query:/app:ro
      - /app/node_modules
    depends_on:
      - event-bus
    command: ["npm", "start"]
  moderation:
    build: 
      context: ./moderation
      args:
        NODE_ENV: development
        PORT: 4003
    ports:
      - "4003:4003"
    environment:
      - PORT=4003
      - NODE_ENV=development
    volumes:
      - ./moderation:/app:ro
      - /app/node_modules
    command: ["npm", "start"]
  event-bus:
    build: 
      context: ./event-bus
      args:
        NODE_ENV: development
        PORT: 4005
    ports:
      - "4005:4005"
    environment:
      - PORT=4005
      - NODE_ENV=development
    volumes:
      - ./event-bus:/app:ro
      - /app/node_modules
    command: ["npm", "start"]
  client:
    build: 
      context: ./client
      args:
        NODE_ENV: development
        PORT: 3000
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./event-bus:/app:ro
      - /app/node_modules
    command: ["npm", "start"]